# This is a basic workflow to help you get started with Actions

name: pull-request

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    types: [synchronize, labeled, closed]
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "github ref" ${{ github.ref }}
          echo "github base_ref" ${{ github.base_ref }}
          echo "github head_ref" ${{ github.head_ref }}
          echo "github.event.pull_request.head.ref" ${{ github.event.pull_request.head.ref }}
          echo "github.event.pull_request.base.ref" ${{ github.event.pull_request.base.ref }}
          
